# Generated by Django 5.2 on 2025-05-05 18:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_userbook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='is_Read',
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, help_text='0–5 stars', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='userbook',
            name='date',
            field=models.DateField(verbose_name='date finished'),
        ),
    ]
