# Generated by Django 5.2 on 2025-05-06 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_book_is_read_book_rating_alter_userbook_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbook',
            old_name='is_read',
            new_name='recommend',
        ),
    ]
